### ISSUE TITLE
[VelocityResourcepacks] NoSuchMethodError when using Velocity 1.1.0 #265 or newer

### ISSUE THREAD

**Issue by Fourmisain** [Phoenix616/ResourcepacksPlugins#44]
VelocityResourcepacks 1.8.2 works with Velocity 1.1.0 up to build #264, any newer version results in the error below.
I tried using VelocityResourcepacks dev build 1.8.3 #356 but it had the same outcome.

#### Full Log
```
[19:34:31] [main/INFO]: Booting up Velocity 1.1.0-SNAPSHOT (git-cfb91046-b276)...
[19:34:32] [main/INFO]: Connections will use NIO channels, Java 11 compression, Java ciphers
[19:34:32] [main/INFO]: Loading plugins...
[19:34:32] [main/INFO]: Loaded plugin velocityresourcepacks 1.8.3-SNAPSHOT (build 356) by Phoenix616
[19:34:32] [main/INFO]: Loaded 1 plugins
[19:34:32] [Velocity Event Executor - #0/INFO]: Loaded config.yml
[19:34:32] [Velocity Event Executor - #0/INFO]: Loaded players.conf
[19:34:32] [Velocity Event Executor - #0/INFO]: Debug level: INFO
[19:34:32] [Velocity Event Executor - #0/INFO]: Found locale en!
[19:34:32] [Velocity Event Executor - #0/INFO]: Loading packs:
[19:34:32] [Velocity Event Executor - #0/INFO]: globalpack - ... - ...
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] {url=..., hash=..., format=6, version=null, restricted=false, permission=velocityresourcepacks.pack.globalpack, variants=null}
[19:34:32] [Velocity Event Executor - #0/INFO]: Empty pack - http://cdn.moep.tv/files/Empty.zip - 01517226212d27586ea0c5d6aff1aa5492dd2484
[19:34:32] [Velocity Event Executor - #0/INFO]: Loading global assignment...
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] Pack: globalpack
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] Send delay: 20
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] Loaded PackAssignment{name=global, pack=globalpack, secondaries=[], sendDelay=20}
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] No server assignments defined!
[19:34:32] [Velocity Event Executor - #0/INFO]: [DEBUG] Stored packs override assignments: false
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: Exception in thread "Velocity Task Scheduler - #0" java.lang.NoSuchMethodError: 'net.kyori.adventure.text.TextComponent$Builder net.kyori.adventure.text.TextComponent.builder(java.lang.String)'
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.libs.minedown.adventure.MineDownParser.appendValue(MineDownParser.java:293)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.libs.minedown.adventure.MineDownParser.appendValue(MineDownParser.java:288)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.libs.minedown.adventure.MineDownParser.parse(MineDownParser.java:272)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.libs.minedown.adventure.MineDown.toComponent(MineDown.java:130)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.libs.minedown.adventure.MineDown.parse(MineDown.java:112)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.getComponents(VelocityResourcepacks.java:543)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.sendMessage(VelocityResourcepacks.java:640)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.sendMessage(VelocityResourcepacks.java:635)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at de.themoep.resourcepacksplugin.core.PackManager.lambda$generateHashes$0(PackManager.java:916)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:185)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:34:32] [Velocity Task Scheduler - #0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[19:34:32] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25577
[19:34:32] [main/INFO]: Done (0.91s)!
```

#### Config
```
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
packs:
  globalpack:
    url: ...
    hash: ...
    format: 6
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: globalpack
  send-delay: 20
```

**Comment by Fourmisain** [comment]
Thanks for the quick response, the build is done and working! :+1:
